merge: updated fork to be based on obnc-0.17.0

diff --git a/bin/obnc-test b/bin/obnc-test
--- a/bin/obnc-test
+++ b/bin/obnc-test
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (C) 2017, 2018, 2019 Karl Landstrom <karl@miasap.se>
+# Copyright 2017, 2018, 2019, 2023 Karl Landstrom <karl@miasap.se>
 #
 # This file is part of OBNC.
 #
@@ -23,12 +23,20 @@ readonly selfDirPath="$(cd "$(dirname "$0")"; pwd -P)"
 readonly packagePath="$(dirname "$selfDirPath")"
 export OBNC_PREFIX="$packagePath"
 export OBNC_LIBDIR="lib"
-export CC="${CC:-}"
+export CC="${CC:-cc}"
 export CFLAGS="${CFLAGS:-} -I$packagePath/lib"
 
-EchoAndRun()
+Log()
 {
-	echo "$@"
+	if "$verbose"; then
+		echo "$@"
+	fi
+}
+
+
+Run()
+{
+	Log "$@"
 	eval "$@"
 }
 
@@ -43,14 +51,20 @@ CleanUp()
 	done
 }
 
+if [ "$#" -eq 1 ] && [ "$1" = -v ]; then
+	verbose=true
+else
+	verbose=false
+fi
+
 CleanUp
 
 dir="$packagePath/tests/obnc/passing"
-EchoAndRun cd "$dir"
+Run cd "$dir"
 for module in *.obn; do
 	if [ "$module" != T5SystemStatements.obn ]; then
-		if EchoAndRun "OBNC_IMPORT_PATH='a dir' $packagePath/bin/obnc" "$module"; then
-			if ! EchoAndRun "./${module%.obn}"; then
+		if Run "OBNC_IMPORT_PATH='a dir' $packagePath/bin/obnc" "$module"; then
+			if ! Run "./${module%.obn}"; then
 				printf "\nPositive test failed: %s\n\n" "$dir/$module">&2
 				exit 1
 			fi
@@ -67,23 +81,26 @@ for def in OBNC_CONFIG_C_INT_TYPE=OBNC_CONFIG_SHORT \
 		OBNC_CONFIG_C_REAL_TYPE=OBNC_CONFIG_FLOAT \
 		OBNC_CONFIG_C_REAL_TYPE=OBNC_CONFIG_DOUBLE \
 		OBNC_CONFIG_C_REAL_TYPE=OBNC_CONFIG_LONG_DOUBLE \
-		 OBNC_CONFIG_TARGET_EMB=1; do
-	if EchoAndRun "CFLAGS='$CFLAGS -D $def' '$packagePath/bin/obnc'" -x A.obn; then
-		if ! EchoAndRun ./A; then
-			printf "\nPositive test compiled with C flag %s failed: %s\n\n" "$cFlag" "$dir/A.obn">&2
+		OBNC_CONFIG_NO_GC=1 \
+		OBNC_CONFIG_TARGET_EMB=1; do
+	if Run "CFLAGS='$CFLAGS -D $def' '$packagePath/bin/obnc'" -x A.obn; then
+		if ! Run ./A; then
+			printf "\nFailed running positive test compiled with C flag %s failed: %s\n\n" "$def" "$dir/A">&2
 			exit 1
 		fi
 	else
-		printf "\nPositive test compiled with C flag %s failed: %s\n\n" "$cFlag" "$dir/A.obn" >&2
+		printf "\nPositive test compiled with C flag %s failed: %s\n\n" "$def" "$dir/A.obn" >&2
 		exit 1
 	fi
 done
 
 dir="$packagePath/tests/obnc/failing-at-compile-time"
-EchoAndRun cd "$dir"
+Run cd "$dir"
+"$packagePath/bin/obnc-compile" A.obn
+"$packagePath/bin/obnc-compile" B.obn
 for module in *.obn; do
 	if [ "$module" != A.obn ] && [ "$module" != B.obn ]; then
-		echo "$packagePath/bin/obnc-compile" "$module"
+		Log "$packagePath/bin/obnc-compile" "$module"
 		if "$packagePath/bin/obnc-compile" "$module" 2>/dev/null; then
 			printf "\nNegative test failed: %s\n\n" "$dir/$module" >&2
 			exit 1
@@ -95,11 +112,11 @@ for module in *.obn; do
 done
 
 dir="$packagePath/tests/obnc/failing-at-runtime"
-EchoAndRun cd "$dir"
+Run cd "$dir"
 for module in *.obn; do
 	if [ "$module" != A.obn ] && [ "$module" != B.obn ]; then
-		if EchoAndRun "$packagePath/bin/obnc" "$module"; then
-			echo "./${module%.obn}"
+		if Run "$packagePath/bin/obnc" "$module"; then
+			Log "./${module%.obn}"
 			if ( "./${module%.obn}" || false ) >/dev/null 2>&1; then
 				printf "\nNegative test failed: %s\n\n" "$dir/$module" >&2
 				exit 1
